### ISSUE TITLE
[FEATURE] Cloudflare KV, Cloudflare Pages 도입(CI/CD 방식 변경)

### ISSUE THREAD

**Issue by CXZ7720** [CXZ7720/Shuttle_PWA#89]
## Describe your feature request
* 시간표 수정때마다 JSON을 수정하지 말고 KV에 저장된 값을 변경시켜서 동적으로 업데이트 할 수 있도록 지원해요
* 웹앱 서비스 자체도 현재의 AppEngine 인스턴스를 띄우는 구조에서 벗어나 CF Pages나 Vercel 같은 JamStack Platform으로 이사해요.

## Advantages of this feature
* 매번 json 파일때문에 빌드 파이프라인을 돌리지 않아도 되므로 비용적인 측면에서 개선시킬 수 있어요.
* GCP를 이용한 CI/CD를 배워보는것도 좋지만, 우리 프로젝트 구조에는 맞지 않는 배포형식이에요. CF Pages로 이사한다면 훨씬 더 가볍고 빠른 배포주기를 가져갈 수 있고, 비용을 획기적으로 줄일 수 있어요.

## Additional context

CloudFlare 서비스를 이용하기 쉽게 도와주는 [worktop](https://www.npmjs.com/package/worktop) 이라는 NPM Package가 있어요.
또한 KV는 wrangler 라는 툴을 이용해 개발/배포 할 수 있어요.

**Comment by Taewan-P** [comment]
해당 이슈는 리뉴얼된 [서비스](https://github.com/BusHanyang/hybus-genesis)를 제작하면서 전부 반영하였습니다.
